/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: LPC845
package_id: LPC845M301JBD48
mcu_data: ksdk2_0
processor_version: 12.0.0
board: LPC845BREAKOUT
pin_labels:
- {pin_num: '14', pin_signal: PIO1_1/CAPT_X2, label: RS485_TXRX_EN, identifier: LED_BLUE;RS485_TXRX_EN}
- {pin_num: '2', pin_signal: PIO0_13/ADC_10, label: M8_STEP, identifier: M8_STEP}
- {pin_num: '4', pin_signal: PIO0_12, label: M8_DIR, identifier: M8_DIR}
- {pin_num: '6', pin_signal: PIO0_4/ADC_11, label: M11_DIR, identifier: K3;M8_DIR;M11_DIR}
- {pin_num: '7', pin_signal: PIO0_28/WKTCLKIN, label: M6_DIR, identifier: M3_DIR;M3_DIR_;M6_DIR}
- {pin_num: '9', pin_signal: PIO0_31/CAPT_X0, label: M7_STEP, identifier: CAPX;M7_STEP}
- {pin_num: '12', pin_signal: PIO0_11/I2C0_SDA, label: M7_STEP, identifier: M7_STEP}
- {pin_num: '13', pin_signal: PIO0_10/I2C0_SCL, label: M7_DIR, identifier: MM;RS;M7_STEP;M7_DIR}
- {pin_num: '15', pin_signal: PIO0_16, label: M0_DIR, identifier: M0_DIR}
- {pin_num: '17', pin_signal: PIO0_27, label: M5_STEP, identifier: M2_STEP;M2_STEP_;M5_STEP}
- {pin_num: '18', pin_signal: PIO0_26, label: M5_DIR, identifier: M2_DIR;M2_DIR_;M5_DIR}
- {pin_num: '19', pin_signal: PIO0_25, label: M11_STEP, identifier: DEBUG_UART_TX;M4_STEP}
- {pin_num: '20', pin_signal: PIO0_24, label: M4_DIR, identifier: DEBUG_UART_RX;M4_DIR}
- {pin_num: '22', pin_signal: PIO0_15, label: M9_STEP, identifier: M9_STEP}
- {pin_num: '24', pin_signal: PIO0_1/ACMP_I2/CLKIN, label: M11_STEP, identifier: RS485_TXRX_EN;Hall_M1;M11_STEP}
- {pin_num: '25', pin_signal: PIO0_9/XTALOUT, label: MAG1, identifier: M7_DIR;MAG1}
- {pin_num: '26', pin_signal: PIO0_8/XTALIN, label: MAG0, identifier: RESET;MAG2;MAG0}
- {pin_num: '33', pin_signal: PIO0_7/ADC_0, label: M10_DIR, identifier: M9_DIR;M10_DIR}
- {pin_num: '34', pin_signal: PIO0_6/ADC_1/ACMPVREF, label: M10_STEP, identifier: M8_STEP;M10_STEP}
- {pin_num: '36', pin_signal: PIO0_0/ACMP_I1, label: DRV_RESET, identifier: Hall_M0;DRV_RESET}
- {pin_num: '37', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: M9_DIR, identifier: M9_DIR}
- {pin_num: '38', pin_signal: PIO0_29/DACOUT_1, label: M6_STEP, identifier: M3_STEP;M3_STEP_;M6_STEP}
- {pin_num: '39', pin_signal: PIO0_23/ADC_3/ACMP_I4, label: M3_STEP, identifier: M3_STEP}
- {pin_num: '42', pin_signal: PIO0_30/ACMP_I5, label: M7_DIR, identifier: CAPY_R;M7_DIR}
- {pin_num: '43', pin_signal: PIO0_22/ADC_4, label: M3_DIR, identifier: Hall_M1;M3_DIR}
- {pin_num: '44', pin_signal: PIO0_21/ADC_5, label: M2_STEP, identifier: Hall_M0;M2_STEP}
- {pin_num: '45', pin_signal: PIO0_20/ADC_6, label: M2_DIR, identifier: RESET;M2_DIR}
- {pin_num: '46', pin_signal: PIO0_19/ADC_7, label: M1_STEP, identifier: M1_STEP}
- {pin_num: '47', pin_signal: PIO0_18/ADC_8, label: M1_DIR, identifier: M1_DIR}
- {pin_num: '48', pin_signal: PIO0_17/ADC_9/DACOUT_0, label: M0_STEP, identifier: M0_STEP}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitMotorPins();
    BOARD_InitMagPins();
    BOARD_InitRS485();
    BOARD_InitSWD_DEBUGPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitMotorPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '15', peripheral: GPIO, signal: 'PIO0, 16', pin_signal: PIO0_16, direction: OUTPUT}
  - {pin_num: '48', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17/ADC_9/DACOUT_0, direction: OUTPUT}
  - {pin_num: '47', peripheral: GPIO, signal: 'PIO0, 18', pin_signal: PIO0_18/ADC_8, direction: OUTPUT}
  - {pin_num: '46', peripheral: GPIO, signal: 'PIO0, 19', pin_signal: PIO0_19/ADC_7, direction: OUTPUT}
  - {pin_num: '45', peripheral: GPIO, signal: 'PIO0, 20', pin_signal: PIO0_20/ADC_6, identifier: M2_DIR, direction: OUTPUT}
  - {pin_num: '44', peripheral: GPIO, signal: 'PIO0, 21', pin_signal: PIO0_21/ADC_5, identifier: M2_STEP, direction: OUTPUT}
  - {pin_num: '43', peripheral: GPIO, signal: 'PIO0, 22', pin_signal: PIO0_22/ADC_4, identifier: M3_DIR, direction: OUTPUT}
  - {pin_num: '39', peripheral: GPIO, signal: 'PIO0, 23', pin_signal: PIO0_23/ADC_3/ACMP_I4, direction: OUTPUT}
  - {pin_num: '20', peripheral: GPIO, signal: 'PIO0, 24', pin_signal: PIO0_24, identifier: M4_DIR, direction: OUTPUT}
  - {pin_num: '19', peripheral: GPIO, signal: 'PIO0, 25', pin_signal: PIO0_25, identifier: M4_STEP, direction: OUTPUT}
  - {pin_num: '18', peripheral: GPIO, signal: 'PIO0, 26', pin_signal: PIO0_26, identifier: M5_DIR, direction: OUTPUT}
  - {pin_num: '17', peripheral: GPIO, signal: 'PIO0, 27', pin_signal: PIO0_27, identifier: M5_STEP, direction: OUTPUT}
  - {pin_num: '7', peripheral: GPIO, signal: 'PIO0, 28', pin_signal: PIO0_28/WKTCLKIN, identifier: M6_DIR, direction: OUTPUT}
  - {pin_num: '38', peripheral: GPIO, signal: 'PIO0, 29', pin_signal: PIO0_29/DACOUT_1, identifier: M6_STEP, direction: OUTPUT}
  - {pin_num: '13', peripheral: GPIO, signal: 'PIO0, 10', pin_signal: PIO0_10/I2C0_SCL, identifier: M7_DIR, direction: OUTPUT, i2cmode: gpioMode}
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/ADC_11, identifier: M11_DIR, direction: OUTPUT}
  - {pin_num: '34', peripheral: GPIO, signal: 'PIO0, 6', pin_signal: PIO0_6/ADC_1/ACMPVREF, identifier: M10_STEP, direction: OUTPUT}
  - {pin_num: '33', peripheral: GPIO, signal: 'PIO0, 7', pin_signal: PIO0_7/ADC_0, identifier: M10_DIR, direction: OUTPUT}
  - {pin_num: '22', peripheral: GPIO, signal: 'PIO0, 15', pin_signal: PIO0_15, direction: OUTPUT}
  - {pin_num: '37', peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/ACMP_I3/ADC_2, direction: OUTPUT}
  - {pin_num: '2', peripheral: GPIO, signal: 'PIO0, 13', pin_signal: PIO0_13/ADC_10, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 12', pin_signal: PIO0_12, direction: OUTPUT}
  - {pin_num: '12', peripheral: GPIO, signal: 'PIO0, 11', pin_signal: PIO0_11/I2C0_SDA, direction: OUTPUT, i2cmode: gpioMode}
  - {pin_num: '24', peripheral: GPIO, signal: 'PIO0, 1', pin_signal: PIO0_1/ACMP_I2/CLKIN, identifier: M11_STEP, direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIO, signal: 'PIO0, 0', pin_signal: PIO0_0/ACMP_I1, identifier: DRV_RESET, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMotorPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitMotorPins(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t gpio0_pin0_0 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_0 (pin )  */
    GPIO_PinInit(GPIO, 0U, 0U, &gpio0_pin0_0);

    gpio_pin_config_t gpio0_pin0_1 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_1 (pin )  */
    GPIO_PinInit(GPIO, 0U, 1U, &gpio0_pin0_1);

    gpio_pin_config_t gpio0_pin0_4 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin )  */
    GPIO_PinInit(GPIO, 0U, 4U, &gpio0_pin0_4);

    gpio_pin_config_t gpio0_pin0_6 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_6 (pin )  */
    GPIO_PinInit(GPIO, 0U, 6U, &gpio0_pin0_6);

    gpio_pin_config_t gpio0_pin0_7 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_7 (pin )  */
    GPIO_PinInit(GPIO, 0U, 7U, &gpio0_pin0_7);

    gpio_pin_config_t M7_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_10 (pin 13)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M7_DIR_GPIO, BOARD_INITMOTORPINS_M7_DIR_PORT, BOARD_INITMOTORPINS_M7_DIR_PIN, &M7_DIR_config);

    gpio_pin_config_t M7_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_11 (pin 12)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M7_STEP_GPIO, BOARD_INITMOTORPINS_M7_STEP_PORT, BOARD_INITMOTORPINS_M7_STEP_PIN, &M7_STEP_config);

    gpio_pin_config_t gpio0_pin0_12 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_12 (pin )  */
    GPIO_PinInit(GPIO, 0U, 12U, &gpio0_pin0_12);

    gpio_pin_config_t gpio0_pin0_13 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_13 (pin )  */
    GPIO_PinInit(GPIO, 0U, 13U, &gpio0_pin0_13);

    gpio_pin_config_t gpio0_pin0_14 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_14 (pin )  */
    GPIO_PinInit(GPIO, 0U, 14U, &gpio0_pin0_14);

    gpio_pin_config_t gpio0_pin0_15 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_15 (pin )  */
    GPIO_PinInit(GPIO, 0U, 15U, &gpio0_pin0_15);

    gpio_pin_config_t M0_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_16 (pin 15)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M0_DIR_GPIO, BOARD_INITMOTORPINS_M0_DIR_PORT, BOARD_INITMOTORPINS_M0_DIR_PIN, &M0_DIR_config);

    gpio_pin_config_t M0_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_17 (pin 48)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M0_STEP_GPIO, BOARD_INITMOTORPINS_M0_STEP_PORT, BOARD_INITMOTORPINS_M0_STEP_PIN, &M0_STEP_config);

    gpio_pin_config_t M1_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_18 (pin 47)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M1_DIR_GPIO, BOARD_INITMOTORPINS_M1_DIR_PORT, BOARD_INITMOTORPINS_M1_DIR_PIN, &M1_DIR_config);

    gpio_pin_config_t M1_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_19 (pin 46)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M1_STEP_GPIO, BOARD_INITMOTORPINS_M1_STEP_PORT, BOARD_INITMOTORPINS_M1_STEP_PIN, &M1_STEP_config);

    gpio_pin_config_t M2_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_20 (pin 45)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M2_DIR_GPIO, BOARD_INITMOTORPINS_M2_DIR_PORT, BOARD_INITMOTORPINS_M2_DIR_PIN, &M2_DIR_config);

    gpio_pin_config_t M2_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_21 (pin 44)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M2_STEP_GPIO, BOARD_INITMOTORPINS_M2_STEP_PORT, BOARD_INITMOTORPINS_M2_STEP_PIN, &M2_STEP_config);

    gpio_pin_config_t M3_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_22 (pin 43)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M3_DIR_GPIO, BOARD_INITMOTORPINS_M3_DIR_PORT, BOARD_INITMOTORPINS_M3_DIR_PIN, &M3_DIR_config);

    gpio_pin_config_t M3_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_23 (pin 39)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M3_STEP_GPIO, BOARD_INITMOTORPINS_M3_STEP_PORT, BOARD_INITMOTORPINS_M3_STEP_PIN, &M3_STEP_config);

    gpio_pin_config_t M4_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_24 (pin 20)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M4_DIR_GPIO, BOARD_INITMOTORPINS_M4_DIR_PORT, BOARD_INITMOTORPINS_M4_DIR_PIN, &M4_DIR_config);

    gpio_pin_config_t M4_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_25 (pin 19)  */
    GPIO_PinInit(BOARD_INITMOTORPINS_M4_STEP_GPIO, BOARD_INITMOTORPINS_M4_STEP_PORT, BOARD_INITMOTORPINS_M4_STEP_PIN, &M4_STEP_config);

    gpio_pin_config_t gpio0_pin0_26 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_26 (pin )  */
    GPIO_PinInit(GPIO, 0U, 26U, &gpio0_pin0_26);

    gpio_pin_config_t gpio0_pin0_27 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_27 (pin )  */
    GPIO_PinInit(GPIO, 0U, 27U, &gpio0_pin0_27);

    gpio_pin_config_t gpio0_pin0_28 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_28 (pin )  */
    GPIO_PinInit(GPIO, 0U, 28U, &gpio0_pin0_28);

    gpio_pin_config_t gpio0_pin0_29 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_29 (pin )  */
    GPIO_PinInit(GPIO, 0U, 29U, &gpio0_pin0_29);

    IOCON->PIO[8] = ((IOCON->PIO[8] &
                      /* Mask bits to zero which are setting */
                      (~(IOCON_PIO_I2CMODE_MASK)))

                     /* Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output
                      * function. */
                     | IOCON_PIO_I2CMODE(PIO0_10_I2CMODE_Standard_GPIO));

    IOCON->PIO[7] = ((IOCON->PIO[7] &
                      /* Mask bits to zero which are setting */
                      (~(IOCON_PIO_I2CMODE_MASK)))

                     /* Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output
                      * function. */
                     | IOCON_PIO_I2CMODE(PIO0_11_I2CMODE_Standard_GPIO));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitMagPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '25', peripheral: GPIO, signal: 'PIO0, 9', pin_signal: PIO0_9/XTALOUT, identifier: MAG1, direction: INPUT}
  - {pin_num: '26', peripheral: GPIO, signal: 'PIO0, 8', pin_signal: PIO0_8/XTALIN, identifier: MAG0, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMagPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitMagPins(void)
{
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t MAG0_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_8 (pin 26)  */
    GPIO_PinInit(BOARD_INITMAGPINS_MAG0_GPIO, BOARD_INITMAGPINS_MAG0_PORT, BOARD_INITMAGPINS_MAG0_PIN, &MAG0_config);

    gpio_pin_config_t MAG1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_9 (pin 25)  */
    GPIO_PinInit(BOARD_INITMAGPINS_MAG1_GPIO, BOARD_INITMAGPINS_MAG1_PORT, BOARD_INITMAGPINS_MAG1_PIN, &MAG1_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitRS485:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '14', peripheral: USART2, signal: RTS, pin_signal: PIO1_1/CAPT_X2, identifier: RS485_TXRX_EN}
  - {pin_num: '16', peripheral: USART2, signal: TXD, pin_signal: PIO1_2/CAPT_X3, identifier: ''}
  - {pin_num: '11', peripheral: USART2, signal: RXD, pin_signal: PIO1_0/CAPT_X1, identifier: ''}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitRS485
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitRS485(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* USART2_TXD connect to P1_2 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART2_TXD, kSWM_PortPin_P1_2);

    /* USART2_RXD connect to P1_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART2_RXD, kSWM_PortPin_P1_0);

    /* USART2_RTS connect to P1_1 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART2_RTS, kSWM_PortPin_P1_1);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSWD_DEBUGPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '8', peripheral: SWD, signal: SWCLK, pin_signal: SWCLK/PIO0_3}
  - {pin_num: '10', peripheral: SWD, signal: SWDIO, pin_signal: SWDIO/PIO0_2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSWD_DEBUGPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitSWD_DEBUGPins(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* SWCLK connect to P0_3 */
    SWM_SetFixedPinSelect(SWM0, kSWM_SWCLK, true);

    /* SWDIO connect to P0_2 */
    SWM_SetFixedPinSelect(SWM0, kSWM_SWDIO, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
