/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output function. */
#define PIO0_10_I2CMODE_Standard_GPIO 0x01u
/*!
 * @brief Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output function. */
#define PIO0_11_I2CMODE_Standard_GPIO 0x01u

/*! @name PIO0_16 (number 15), M0_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M0_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M0_DIR_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M0_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M0_DIR_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M0_DIR_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_17 (number 48), M0_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M0_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M0_STEP_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M0_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M0_STEP_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M0_STEP_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_18 (number 47), M1_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M1_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M1_DIR_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M1_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M1_DIR_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M1_DIR_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_19 (number 46), M1_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M1_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M1_STEP_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M1_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M1_STEP_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M1_STEP_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_20 (number 45), M2_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M2_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M2_DIR_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M2_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M2_DIR_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M2_DIR_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_21 (number 44), M2_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M2_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M2_STEP_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M2_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M2_STEP_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M2_STEP_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_22 (number 43), M3_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M3_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M3_DIR_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M3_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M3_DIR_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M3_DIR_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_23 (number 39), M3_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M3_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M3_STEP_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M3_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M3_STEP_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M3_STEP_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_24 (number 20), M4_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M4_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M4_DIR_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M4_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M4_DIR_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M4_DIR_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_25 (number 19), M11_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M4_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M4_STEP_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M4_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M4_STEP_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M4_STEP_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_26 (number 18), M5_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M5_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M5_DIR_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M5_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M5_DIR_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M5_DIR_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_27 (number 17), M5_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M5_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M5_STEP_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M5_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M5_STEP_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M5_STEP_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_28 (number 7), M6_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M6_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M6_DIR_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M6_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M6_DIR_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M6_DIR_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_29 (number 38), M6_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M6_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M6_STEP_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M6_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M6_STEP_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M6_STEP_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_10 (number 13), M7_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M7_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M7_DIR_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M7_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M7_DIR_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M7_DIR_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_4 (number 6), M11_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M11_DIR_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M11_DIR_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M11_DIR_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M11_DIR_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M11_DIR_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_6 (number 34), M10_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M10_STEP_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M10_STEP_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M10_STEP_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M10_STEP_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M10_STEP_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_7 (number 33), M10_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M10_DIR_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M10_DIR_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M10_DIR_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M10_DIR_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M10_DIR_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_15 (number 22), M9_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M9_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M9_STEP_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M9_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M9_STEP_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M9_STEP_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_14 (number 37), M9_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M9_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M9_DIR_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M9_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M9_DIR_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M9_DIR_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_13 (number 2), M8_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M8_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M8_STEP_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M8_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M8_STEP_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M8_STEP_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_12 (number 4), M8_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M8_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M8_DIR_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M8_DIR_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M8_DIR_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M8_DIR_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_11 (number 12), M7_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M7_STEP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M7_STEP_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M7_STEP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M7_STEP_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M7_STEP_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_1 (number 24), M11_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_M11_STEP_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_M11_STEP_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_M11_STEP_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_M11_STEP_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_M11_STEP_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_0 (number 36), DRV_RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMOTORPINS_DRV_RESET_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMOTORPINS_DRV_RESET_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_INITMOTORPINS_DRV_RESET_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITMOTORPINS_DRV_RESET_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORPINS_DRV_RESET_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMotorPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO0_9 (number 25), MAG1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMAGPINS_MAG1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMAGPINS_MAG1_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */
#define BOARD_INITMAGPINS_MAG1_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITMAGPINS_MAG1_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITMAGPINS_MAG1_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_8 (number 26), MAG0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMAGPINS_MAG0_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMAGPINS_MAG0_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define BOARD_INITMAGPINS_MAG0_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITMAGPINS_MAG0_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITMAGPINS_MAG0_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMagPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO1_1 (number 14), RS485_TXRX_EN
  @{ */
#define BOARD_INITRS485_RS485_TXRX_EN_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITRS485_RS485_TXRX_EN_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITRS485_RS485_TXRX_EN_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitRS485(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
